package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/webomindapps-dev/coolaid-backend/internal/api/graphql/helpers"
	mapping "github.com/webomindapps-dev/coolaid-backend/internal/api/graphql/mappers/master"
	product_mapper "github.com/webomindapps-dev/coolaid-backend/internal/api/graphql/mappers/product"
	"github.com/webomindapps-dev/coolaid-backend/internal/domain/auth"
	"github.com/webomindapps-dev/coolaid-backend/internal/domain/product"
	graphql1 "github.com/webomindapps-dev/coolaid-backend/internal/generated/graphql"
	"github.com/webomindapps-dev/coolaid-backend/internal/generated/graphql/model"
	"github.com/webomindapps-dev/coolaid-backend/internal/shared/ptr"
	"github.com/webomindapps-dev/coolaid-backend/oplog"
)

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	res, err := r.Resolver.Services.Auth.DB.Queries().GetUserById(ctx, auth.ID(id.String()))

	if err != nil {
		return nil, mapAuthError(err)
	}

	u, err := res.ID.ToUUID(ctx)

	return &model.User{
		ID:       u,
		Name:     res.Name,
		Username: res.Username,
		Email:    res.Email,
		Mobile:   res.Mobile,
		Role:     res.Role,
		IsActive: res.IsActive,
	}, nil
}

// GetLatestOtp is the resolver for the getLatestOTP field.
func (r *queryResolver) GetLatestOtp(ctx context.Context, userID uuid.UUID) (*model.UserOtp, error) {
	row, err := r.Resolver.Services.Auth.DB.Queries().GetLatestOTPFromUser(ctx, auth.ID(userID.String()))
	if err != nil {
		oplog.Error(ctx,
			"GetLatestOtp failed",
			"user_id=", userID.String(),
			"err=", err,
		)
		return nil, mapAuthError(err)
	}

	uid, err := row.UserID.ToUUID(ctx)
	if err != nil {
		oplog.Error(ctx,
			"GetLatestOtp: invalid user UUID returned from DB",
			"user_id=", row.UserID,
			"err=", err,
		)
		return nil, gqlerror.Errorf("internal error")
	}

	oid, err := row.UserID.ToUUID(ctx) // if OTP row has ID, else remove this
	if err != nil {
		oplog.Error(ctx,
			"GetLatestOtp: invalid otp UUID returned from DB",
			"otp_id=", row.UserID,
			"err=", err,
		)
		return nil, gqlerror.Errorf("internal error")
	}

	oplog.Info(ctx,
		"GetLatestOtp success",
		"user_id=", userID.String(),
	)

	return &model.UserOtp{
		ID:      oid, // remove if not in gql model
		UserID:  uid,
		OtpCode: row.OtpCode, // adjust field name if different
	}, nil
}

// GetSessionByUserID is the resolver for the getSessionByUserId field.
func (r *queryResolver) GetSessionByUserID(ctx context.Context, userID uuid.UUID) (*model.UserSession, error) {
	row, err := r.Resolver.Services.Auth.DB.Queries().GetUserSessionById(ctx, auth.ID(userID.String()))
	if err != nil {
		oplog.Error(ctx,
			"GetSessionByUserID failed",
			"user_id=", userID.String(),
			"err=", err,
		)
		return nil, mapAuthError(err)
	}

	sid, err := row.UserID.ToUUID(ctx)
	if err != nil {
		oplog.Error(ctx,
			"GetSessionByUserID: invalid session UUID returned from DB",
			"id=", row.UserID,
			"err=", err,
		)
		return nil, gqlerror.Errorf("internal error")
	}

	uid, err := row.UserID.ToUUID(ctx)
	if err != nil {
		oplog.Error(ctx,
			"GetSessionByUserID: invalid user UUID returned from DB",
			"user_id=", row.UserID,
			"err=", err,
		)
		return nil, gqlerror.Errorf("internal error")
	}

	oplog.Info(ctx,
		"GetSessionByUserID success",
		"user_id=", userID.String(),
		"session_id=", sid.String(),
	)

	return &model.UserSession{
		SessionID: sid,
		UserID:    uid,
		ExpiresAt: row.ExpiresAt,
	}, nil
}

// GetSessionStatus is the resolver for the getSessionStatus field.
func (r *queryResolver) GetSessionStatus(ctx context.Context, sessionID uuid.UUID) (*model.SessionStatus, error) {
	_, err := r.Resolver.Services.Auth.DB.Queries().GetUserSessionById(ctx, auth.ID(sessionID.String()))
	if err != nil {
		oplog.Error(ctx,
			"GetSessionStatus failed",
			"session_id=", sessionID.String(),
			"err=", err,
		)
		return nil, mapAuthError(err)
	}

	oplog.Info(ctx,
		"GetSessionStatus success",
		"session_id=", sessionID.String(),
	)

	return &model.SessionStatus{
		Valid: true,
	}, nil
}

// GetCompanyListByName is the resolver for the getCompanyListByName field.
func (r *queryResolver) GetCompanyListByName(ctx context.Context, name *string) ([]*model.Company, error) {
	res, err := r.Resolver.Services.Company.ListByName(ctx, name)
	if err != nil {
		oplog.Error(ctx,
			"ListByName failed",
			"entity=", "company",
			"name=", name,
			"err=", err,
		)
		return nil, mapCompanyError(err)
	}

	companies, err := mapping.CompaniesToGraphQL(res)
	if err != nil {
		oplog.Error(ctx,
			"Company mapping failed ",
			"entity=", "company",
			"err=", err,
		)
		return nil, gqlerror.Errorf("internal error")
	}

	return companies, nil
}

// GetModelsListByName is the resolver for the getModelsListByName field.
func (r *queryResolver) GetModelsListByName(ctx context.Context, input model.ModelQueryInput) ([]*model.ModelQuery, error) {
	res, err := r.Resolver.Services.Model.ListByName(ctx, &input.Model, &input.Company) // adjust service call
	if err != nil {
		oplog.Error(ctx,
			"GetModelsListByName failed",
			"input=", input,
			"err=", err,
		)
		return nil, mapCompanyError(err)
	}

	oplog.Info(ctx,
		"GetModelsListByName success",
		"count=", len(res),
	)

	// If you already have mapping.ModelQueriesToGraphQL(res) use that instead
	out := make([]*model.ModelQuery, 0, len(res))
	for _, m := range res {
		u, errUUID := uuid.Parse(m.ID)

		if errUUID != nil {
			oplog.Error(ctx,
				"GetModelsListByName error",
				"error=", errUUID,
			)
			continue
		}
		out = append(out, &model.ModelQuery{
			ID:      u,
			Company: m.CompanyName,
			Model:   m.Name,
			Image:   m.ImageURL,
		})
	}
	return out, nil
}

// GetCategoryByName is the resolver for the getCategoryByName field.
func (r *queryResolver) GetCategoryByName(ctx context.Context, category string) ([]*string, error) {
	res, err := r.Resolver.Services.Category.DB.Queries().GetCategoriesByName(ctx, category) // adjust
	if err != nil {
		oplog.Error(ctx,
			"GetCategoryByName failed",
			"category=", category,
			"err=", err,
		)
		return nil, mapCompanyError(err)
	}

	out := make([]*string, 0, len(res))
	for i := range res {
		v := res[i]
		out = append(out, &v.Name)
	}

	oplog.Info(ctx,
		"GetCategoryByName success",
		"query=", category,
		"count=", len(out),
	)

	return out, nil
}

// GetCategoryListByName is the resolver for the getCategoryListByName field.
func (r *queryResolver) GetCategoryListByName(ctx context.Context, category string) ([]*model.Category, error) {
	res, err := r.Resolver.Services.Category.ListByName(ctx, category) // adjust
	if err != nil {
		oplog.Error(ctx,
			"GetCategoryListByName failed",
			"category=", category,
			"err=", err,
		)
		return nil, err
	}

	oplog.Info(ctx,
		"GetCategoryListByName success",
		"query=", category,
		"count=", len(res),
	)

	out := make([]*model.Category, 0, len(res))
	for _, c := range res {
		u, errUUID := uuid.Parse(c.ID)

		if errUUID != nil {
			oplog.Error(ctx, "GetCategoryList error", "query=", category, "err", errUUID)
			continue
		}
		out = append(out, &model.Category{
			ID:    u,
			Name:  c.Name,
			Image: *c.Image,
		})
	}

	return out, nil
}

// GetBrandListByName is the resolver for the getBrandListByName field.
func (r *queryResolver) GetBrandListByName(ctx context.Context, brand string) ([]*model.Brand, error) {
	res, err := r.Resolver.Services.Brand.ListByName(ctx, &brand)
	if err != nil {
		oplog.Error(ctx,
			"GetBrandListByName failed",
			"brand=", brand,
			"err=", err,
		)
		return nil, err
	}

	oplog.Info(ctx,
		"GetBrandListByName success",
		"query=", brand,
		"count=", len(res),
	)

	out := make([]*model.Brand, 0, len(res))
	for _, b := range res {
		u, errUUID := uuid.Parse(b.ID)

		if errUUID != nil {
			oplog.Error(ctx, "GetBrandListByName", "error=", errUUID)
			continue
		}
		out = append(out, &model.Brand{
			ID:    u,
			Name:  b.Name,
			Image: b.Image,
		})
	}

	return out, nil
}

// GetTypeListByName is the resolver for the getTypeListByName field.
func (r *queryResolver) GetTypeListByName(ctx context.Context, input model.TypeSelectionInput) ([]string, error) {
	panic(fmt.Errorf("not implemented: GetTypeListByName - getTypeListByName"))
}

// GetCustomerByID is the resolver for the getCustomerById field.
func (r *queryResolver) GetCustomerByID(ctx context.Context, customerID uuid.UUID) (*model.Customer, error) {
	res, err := r.Resolver.Services.Customer.GetByID(ctx, customerID.String()) // adjust
	if err != nil {
		oplog.Error(ctx,
			"GetCustomerByID failed",
			"customer_id=", customerID.String(),
			"err=", err,
		)
		return nil, mapCompanyError(err)
	}

	u, err := uuid.Parse(res.ID)
	if err != nil {
		oplog.Error(ctx,
			"GetCustomerByID: invalid UUID returned from domain",
			"id=", res.ID,
			"err=", err,
		)
		return nil, gqlerror.Errorf("internal error")
	}

	oplog.Info(ctx,
		"GetCustomerByID success",
		"customer_id=", res.ID,
	)

	return &model.Customer{
		ID:                  u,
		CustomerCompanyName: res.CustomerCompanyName,
		ContactPerson:       res.ContactPerson,
		Mobile:              res.Mobile,
		Type:                res.Type,
		CustomerDesignation: &res.CustomerDesignation,
		Address:             *res.Address,
		Flat:                *res.Flat,
		Street:              *res.Street,
		City:                res.City,
		State:               res.State,
		Pincode:             *res.Pincode,
		PaymentMode:         res.PaymentMode,
	}, nil
}

// GetCustomersByAttributes is the resolver for the getCustomersByAttributes field.
func (r *queryResolver) GetCustomersByAttributes(ctx context.Context, customerCompanyName *string, contactPerson *string, mobile *string) ([]*model.Customer, error) {

	customerCompany := ptr.String(customerCompanyName)
	contact := ptr.String(contactPerson)
	mobileNo := ptr.String(mobile)

	res, err := r.Resolver.Services.Customer.Search(ctx, &customerCompany, &contact, &mobileNo)
	if err != nil {
		oplog.Error(ctx,
			"GetCustomersByAttributes failed",
			"customer_company_name=", customerCompanyName,
			"contact_person=", contactPerson,
			"mobile=", mobile,
			"err=", err,
		)
		return nil, err
	}

	out := make([]*model.Customer, 0, len(res))

	for _, c := range res {
		u, err := uuid.Parse(c.ID)
		if err != nil {
			oplog.Error(ctx,
				"GetCustomersByAttributes: invalid UUID returned from domain",
				"id=", c.ID,
				"err=", err,
			)
			return nil, gqlerror.Errorf("internal error")
		}

		out = append(out, &model.Customer{
			ID:                  u,
			CustomerCompanyName: c.CustomerCompanyName,
			ContactPerson:       c.ContactPerson,
			Mobile:              c.Mobile,
			Type:                c.Type,

			CustomerDesignation: ptr.StringPtr(&c.CustomerDesignation),

			Address:     ptr.String(c.Address),
			Flat:        ptr.String(c.Flat),
			Street:      ptr.String(c.Street),
			City:        c.City,
			State:       c.State,
			Pincode:     ptr.String(c.Pincode),
			PaymentMode: c.PaymentMode,
		})

	}

	oplog.Info(ctx,
		"GetCustomersByAttributes success",
		"count=", len(out),
	)

	return out, nil
}

// GetVendors is the resolver for the getVendors field.
func (r *queryResolver) GetVendors(ctx context.Context, name *string) ([]*model.Vendor, error) {
	res, err := r.Resolver.Services.Vendor.List(ctx, name) // adjust
	if err != nil {
		oplog.Error(ctx,
			"GetVendors failed",
			"name=", name,
			"err=", err,
		)
		return nil, mapCompanyError(err)
	}

	out := make([]*model.Vendor, 0, len(res))

	for _, v := range res {
		uid, err := uuid.Parse(v.ID)
		if err != nil {
			oplog.Error(ctx,
				"GetVendors: invalid UUID returned from domain",
				"id=", v.ID,
				"err=", err,
			)
			return nil, gqlerror.Errorf("internal error")
		}

		contacts := make([]*model.VendorContact, 0, len(v.VendorContacts))

		for _, contact := range v.VendorContacts {

			contacts = append(contacts, &model.VendorContact{
				ContactPerson: contact.ContactPerson,
				MobileNumber:  contact.MobileNumber,
				EmailID:       contact.EmailID,
			})
		}

		out = append(out, &model.Vendor{
			ID:             uid,
			CompanyName:    v.CompanyName,
			VendorContacts: contacts,
			// If your gql Vendor includes contacts, map them here too.
		})
	}

	oplog.Info(ctx,
		"GetVendors success",
		"name=", name,
		"count=", len(out),
	)

	return out, nil
}

// GetFilteredPartNo is the resolver for the getFilteredPartNo field.
// GetFilteredPartNo resolves the getFilteredPartNo query.
func (r *queryResolver) GetFilteredPartNo(
	ctx context.Context,
	partNo *string,
) ([]string, error) {

	if partNo == nil || *partNo == "" {
		return nil, gqlerror.Errorf("part number is required")
	}

	rows, err := r.Services.Product.GetProductPartNos(ctx, *partNo)
	if err != nil {
		return nil, mapProductError(err)
	}

	return rows, nil
}

// GetFilteredParts is the resolver for the getFilteredParts field.
// GetFilteredParts resolves the getFilteredParts query.
func (r *queryResolver) GetFilteredParts(
	ctx context.Context,
	filter model.FilterInput,
) (*model.FilteredResponse, error) {

	selfSubFields := helpers.GetRequestedSubFields(ctx, "self")
	unicodeSubFields := helpers.GetRequestedSubFields(ctx, "unicode")

	filteredResp, err := r.Services.Product.GetFilterPageDetails(
		ctx,
		product.FilterSelectionParams{
			Company:  filter.CompanyName,
			Model:    filter.ModelName,
			Category: filter.CategoryName,
			Brand:    filter.BrandName,
			Unicode:  filter.Unicode,
		},
		selfSubFields,
		unicodeSubFields,
	)
	if err != nil {
		return nil, mapProductError(err)
	}

	self := make([]*model.FilterOrigin, 0, len(filteredResp.Self))
	for _, item := range filteredResp.Self {
		self = append(self, product_mapper.ToFilterOrigin(item))
	}

	unicode := make([]*model.FilterOrigin, 0, len(filteredResp.Unicode))
	for _, item := range filteredResp.Unicode {
		unicode = append(unicode, product_mapper.ToFilterOrigin(item))
	}

	return &model.FilteredResponse{
		Self:    self,
		Unicode: unicode,
	}, nil
}

// GetProductPartNo is the resolver for the getProductPartNo field.
func (r *queryResolver) GetProductPartNo(ctx context.Context, partNo string) ([]string, error) {
	panic(fmt.Errorf("not implemented: GetProductPartNo - getProductPartNo"))
}

// GetProductDetails is the resolver for the getProductDetails field.
func (r *queryResolver) GetProductDetails(ctx context.Context, productDetails model.ProductDetailsInput) ([]*model.ProductDetails, error) {
	panic(fmt.Errorf("not implemented: GetProductDetails - getProductDetails"))
}

// GetSimilarPricing is the resolver for the getSimilarPricing field.
func (r *queryResolver) GetSimilarPricing(ctx context.Context, input *model.SimilarPricingInput) ([]*model.SimilarPricing, error) {
	panic(fmt.Errorf("not implemented: GetSimilarPricing - getSimilarPricing"))
}

// GetTicketDetails is the resolver for the getTicketDetails field.
func (r *queryResolver) GetTicketDetails(ctx context.Context, input *model.FilterTicketInput) ([]*model.OrderTicket, error) {
	panic(fmt.Errorf("not implemented: GetTicketDetails - getTicketDetails"))
}

// GetOutOfStockList is the resolver for the getOutOfStockList field.
func (r *queryResolver) GetOutOfStockList(ctx context.Context) ([]*model.OutOfStockItem, error) {
	panic(fmt.Errorf("not implemented: GetOutOfStockList - getOutOfStockList"))
}

// GetPlacedOrders is the resolver for the getPlacedOrders field.
func (r *queryResolver) GetPlacedOrders(ctx context.Context) ([]*model.RestockOrdersByDate, error) {
	panic(fmt.Errorf("not implemented: GetPlacedOrders - getPlacedOrders"))
}

// GetActuatorByPartNo is the resolver for the getActuatorByPartNo field.
func (r *queryResolver) GetActuatorByPartNo(ctx context.Context, partNo string) (*model.Actuator, error) {
	panic(fmt.Errorf("not implemented: GetActuatorByPartNo - getActuatorByPartNo"))
}

// GetBlowerMotorByPartNo is the resolver for the getBlowerMotorByPartNo field.
func (r *queryResolver) GetBlowerMotorByPartNo(ctx context.Context, partNo string) (*model.BlowerMotor, error) {
	panic(fmt.Errorf("not implemented: GetBlowerMotorByPartNo - getBlowerMotorByPartNo"))
}

// GetCabinFilterByPartNo is the resolver for the getCabinFilterByPartNo field.
func (r *queryResolver) GetCabinFilterByPartNo(ctx context.Context, partNo string) (*model.CabinFilter, error) {
	panic(fmt.Errorf("not implemented: GetCabinFilterByPartNo - getCabinFilterByPartNo"))
}

// GetChillerUnitByPartNo is the resolver for the getChillerUnitByPartNo field.
func (r *queryResolver) GetChillerUnitByPartNo(ctx context.Context, partNo string) (*model.ChillerUnit, error) {
	panic(fmt.Errorf("not implemented: GetChillerUnitByPartNo - getChillerUnitByPartNo"))
}

// GetClutchAssyByPartNo is the resolver for the getClutchAssyByPartNo field.
func (r *queryResolver) GetClutchAssyByPartNo(ctx context.Context, partNo string) (*model.ClutchAssy, error) {
	panic(fmt.Errorf("not implemented: GetClutchAssyByPartNo - getClutchAssyByPartNo"))
}

// GetCompressorValveByPartNo is the resolver for the getCompressorValveByPartNo field.
func (r *queryResolver) GetCompressorValveByPartNo(ctx context.Context, partNo string) (*model.CompressorValve, error) {
	panic(fmt.Errorf("not implemented: GetCompressorValveByPartNo - getCompressorValveByPartNo"))
}

// GetCondFanAssyByPartNo is the resolver for the getCondFanAssyByPartNo field.
func (r *queryResolver) GetCondFanAssyByPartNo(ctx context.Context, partNo string) (*model.CondFanAssy, error) {
	panic(fmt.Errorf("not implemented: GetCondFanAssyByPartNo - getCondFanAssyByPartNo"))
}

// GetCondenserByPartNo is the resolver for the getCondenserByPartNo field.
func (r *queryResolver) GetCondenserByPartNo(ctx context.Context, partNo string) (*model.Condenser, error) {
	panic(fmt.Errorf("not implemented: GetCondenserByPartNo - getCondenserByPartNo"))
}

// GetEvaporatorByPartNo is the resolver for the getEvaporatorByPartNo field.
func (r *queryResolver) GetEvaporatorByPartNo(ctx context.Context, partNo string) (*model.Evaporator, error) {
	panic(fmt.Errorf("not implemented: GetEvaporatorByPartNo - getEvaporatorByPartNo"))
}

// GetExpansionValveByPartNo is the resolver for the getExpansionValveByPartNo field.
func (r *queryResolver) GetExpansionValveByPartNo(ctx context.Context, partNo string) (*model.ExpansionValve, error) {
	panic(fmt.Errorf("not implemented: GetExpansionValveByPartNo - getExpansionValveByPartNo"))
}

// GetFilterDrierByPartNo is the resolver for the getFilterDrierByPartNo field.
func (r *queryResolver) GetFilterDrierByPartNo(ctx context.Context, partNo string) (*model.FilterDrier, error) {
	panic(fmt.Errorf("not implemented: GetFilterDrierByPartNo - getFilterDrierByPartNo"))
}

// GetHeaterCoreByPartNo is the resolver for the getHeaterCoreByPartNo field.
func (r *queryResolver) GetHeaterCoreByPartNo(ctx context.Context, partNo string) (*model.HeaterCore, error) {
	panic(fmt.Errorf("not implemented: GetHeaterCoreByPartNo - getHeaterCoreByPartNo"))
}

// GetIntercoolerByPartNo is the resolver for the getIntercoolerByPartNo field.
func (r *queryResolver) GetIntercoolerByPartNo(ctx context.Context, partNo string) (*model.Intercooler, error) {
	panic(fmt.Errorf("not implemented: GetIntercoolerByPartNo - getIntercoolerByPartNo"))
}

// GetPressureSwitchByPartNo is the resolver for the getPressureSwitchByPartNo field.
func (r *queryResolver) GetPressureSwitchByPartNo(ctx context.Context, partNo string) (*model.PressureSwitch, error) {
	panic(fmt.Errorf("not implemented: GetPressureSwitchByPartNo - getPressureSwitchByPartNo"))
}

// GetRadiatorByPartNo is the resolver for the getRadiatorByPartNo field.
func (r *queryResolver) GetRadiatorByPartNo(ctx context.Context, partNo string) (*model.Radiator, error) {
	panic(fmt.Errorf("not implemented: GetRadiatorByPartNo - getRadiatorByPartNo"))
}

// GetRadFanAssyByPartNo is the resolver for the getRadFanAssyByPartNo field.
func (r *queryResolver) GetRadFanAssyByPartNo(ctx context.Context, partNo string) (*model.RadFanAssy, error) {
	panic(fmt.Errorf("not implemented: GetRadFanAssyByPartNo - getRadFanAssyByPartNo"))
}

// GetRadFanMotorByPartNo is the resolver for the getRadFanMotorByPartNo field.
func (r *queryResolver) GetRadFanMotorByPartNo(ctx context.Context, partNo string) (*model.RadFanMotor, error) {
	panic(fmt.Errorf("not implemented: GetRadFanMotorByPartNo - getRadFanMotorByPartNo"))
}

// GetResistorByPartNo is the resolver for the getResistorByPartNo field.
func (r *queryResolver) GetResistorByPartNo(ctx context.Context, partNo string) (*model.Resistor, error) {
	panic(fmt.Errorf("not implemented: GetResistorByPartNo - getResistorByPartNo"))
}

// GetRotorByPartNo is the resolver for the getRotorByPartNo field.
func (r *queryResolver) GetRotorByPartNo(ctx context.Context, partNo string) (*model.Rotor, error) {
	panic(fmt.Errorf("not implemented: GetRotorByPartNo - getRotorByPartNo"))
}

// GetStatorByPartNo is the resolver for the getStatorByPartNo field.
func (r *queryResolver) GetStatorByPartNo(ctx context.Context, partNo string) (*model.Stator, error) {
	panic(fmt.Errorf("not implemented: GetStatorByPartNo - getStatorByPartNo"))
}

// GetCompressorByPartNo is the resolver for the getCompressorByPartNo field.
func (r *queryResolver) GetCompressorByPartNo(ctx context.Context, partNo string) (*model.Compressor, error) {
	panic(fmt.Errorf("not implemented: GetCompressorByPartNo - getCompressorByPartNo"))
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
